#! /bin/sh
# /etc/init.d/cbinario-init
 
### BEGIN INIT INFO
# Provides:          cbinario-init
# Required-Start:    $all
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script de ejemplo de arranque automático
# Description:       Script para arrancar el contador binario
### END INIT INFO
 
 
# Dependiendo de los parámetros que se le pasen al programa se usa una opción u otra
case "$1" in
 start)
   echo "Arrancando cbinario-init"
   # Aquí hay que poner el programa que quieras arrancar automáticamente
   /usr/bin/python /home/pi/Documents/contadorBinario.py
   ;;
 stop)
   echo "Deteniendo cbinario-init"
 
   ;;
 *)
   echo "Modo de uso: /etc/init.d/cbinario-init {start|stop}"
   exit 1
   ;;
esac
 
exit 0